# adapted from: https://kinvolk.io/docs/flatcar-container-linux/latest/container-runtimes/switching-from-docker-to-containerd-for-kubernetes/
version = 2

# persistent data location
root = "/var/lib/containerd"
# runtime state information
state = "/run/docker/libcontainerd/containerd"
# set containerd as a subreaper on linux when it is not running as PID 1
subreaper = true
# set containerd's OOM score
oom_score = -999
# CRI plugin listens on a TCP port by default
disabled_plugins = []

# grpc configuration
[grpc]
  address = "/run/docker/libcontainerd/docker-containerd.sock"
  # socket uid
  uid = 0
  # socket gid
  gid = 0

[plugins."io.containerd.runtime.v1.linux"]
  # shim binary name/path
  shim = "containerd-shim"
  # runtime binary name/path
  runtime = "runc"
  # do not use a shim when starting containers, saves on memory but
  # live restore is not supported
  no_shim = false
  # display shim logs in the containerd daemon's log output
  shim_debug = true

[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
  endpoint = ["${dockerhub_mirror_endpoint}"]

[plugins."io.containerd.grpc.v1.cri".registry.auths."registry-1.docker.io"]
  auth = "${dockerhub_auth}"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
