server = "https://docker.io"

[host."${dockerhub_mirror_endpoint}"]
  capabilities = ["pull", "resolve"]
  skip_verify = true

# Fallback in case registry-mirror is down
#
# https://github.com/containerd/containerd/blob/main/docs/hosts.md#server-field
# > the hosts are tried first in the order listed
[host."https://registry-1.docker.io"]
  capabilities = ["pull", "resolve"]
  [host."https://registry-1.docker.io".header]
    Authorization = "Basic ${dockerhub_auth}"
