#!/bin/bash

set -o errexit

version=$(head -c 5 <<< "${kube_version}").0

wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$${version}/crictl-$${version}-linux-amd64.tar.gz
tar zxvf crictl-$${version}-linux-amd64.tar.gz -C /opt/bin
rm -f crictl-$${version}-linux-amd64.tar.gz
