---
apiVersion: v1
metadata:
  name: kube-scheduler-config
  namespace: kube-system
data:
  kubeconfig: |-
    apiVersion: v1
    kind: Config
    clusters:
    - name: local
      cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://127.0.0.1:443
    users:
    - name: kube-scheduler
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: local
        user: kube-scheduler
      name: kube-scheduler-context
    current-context: kube-scheduler-context

  config: |-
    apiVersion: componentconfig/v1alpha1
    kind: KubeSchedulerConfiguration
    clientConnection:
      kubeconfig: /var/lib/kube-scheduler/kubeconfig
    leaderElection:
      leaderElect: true

---
apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    app: kube-scheduler
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: ${hyperkube_image_url}:${hyperkube_image_tag}
    command:
    - /hyperkube
    - scheduler
    - --config=/var/lib/kube-scheduler/config
    - --v=0
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
      - mountPath: /var/lib/kube-scheduler
        name: kube-scheduler-kubeconfig
        readOnly: true
    volumes:
      - name: kube-scheduler-kubeconfig
        configMap:
          name: kube-scheduler-kubeconfig
