apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    app: kube-scheduler
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: ${hyperkube_image_url}:${hyperkube_image_tag}
    command:
    - /hyperkube
    - scheduler
    - --config=/etc/kubernetes/config/kube-scheduler-config.yaml
    - --v=0
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/config
      name: kubernetes-configurations
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/config
    name: kubernetes-configurations
