apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    app: kube-scheduler
spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: registry.k8s.io/kube-scheduler:${kubernetes_version}
      command:
        - kube-scheduler
        ${feature_gates == "" ? "" : "- --feature-gates=${feature_gates}"}
        - --authentication-kubeconfig=/etc/kubernetes/config/scheduler.conf
        - --authorization-kubeconfig=/etc/kubernetes/config/scheduler.conf
        - --config=/etc/kubernetes/config/kube-scheduler-config.yaml
        - --v=0
      livenessProbe:
        httpGet:
          host: 127.0.0.1
          scheme: HTTPS
          path: /healthz
          port: 10259
        initialDelaySeconds: 15
        timeoutSeconds: 15
      # https://github.com/kubernetes/kubernetes/issues/129880
      resources:
        limits:
          cpu: "7"
          memory: 4Gi
        requests:
          cpu: "0"
          memory: 0Mi
      volumeMounts:
        - mountPath: /etc/kubernetes/config
          name: kubernetes-configurations
          readOnly: true
        - mountPath: /etc/kubernetes/ssl
          name: kubernetes-ssl
          readOnly: true
  volumes:
    - hostPath:
        path: /etc/kubernetes/config
      name: kubernetes-configurations
    - hostPath:
        path: /etc/kubernetes/ssl
      name: kubernetes-ssl
