apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: ${hyperkube_image_url}:${hyperkube_image_tag}
    command:
    - /hyperkube
    - apiserver
    - --etcd-servers=${etcd_endpoints}
    - --etcd-cafile=/etc/kubernetes/ssl/ca.pem
    - --etcd-certfile=/etc/kubernetes/ssl/k8s-apiserver.pem
    - --etcd-keyfile=/etc/kubernetes/ssl/k8s-apiserver-key.pem
    - --allow-privileged=true
    - --service-cluster-ip-range=${service_network}
    - --secure-port=443
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota
    - --tls-cert-file=/etc/kubernetes/ssl/k8s-apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/k8s-apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/k8s-apiserver-key.pem
    - --service-account-lookup=true
    - --runtime-config=extensions/v1beta1=true,extensions/v1beta1/deployments=true,extensions/v1beta1/daemonsets=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/thirdpartyresources=true,rbac.authorization.k8s.io/v1beta1=true,batch/v2alpha1=true
    ${cloud_provider == "" ? "" : "- --cloud-provider=${cloud_provider}"}
    - --oidc-issuer-url=${oidc_issuer_url}
    - --oidc-username-claim=email
    - --oidc-client-id=${oidc_client_id}
    - --authorization-rbac-super-user=k8s-admin
    - --authorization-mode=RBAC
    - --apiserver-count=${master_instance_count}
    - --audit-log-path=/var/log/kube-api-server/audit
    - --v=0
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /var/log/kube-api-server
      name: var-log-kube-api-server
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - hostPath:
      path: /var/log/kube-api-server
    name: var-log-kube-api-server
