apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    app: kube-scheduler
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: ${hyperkube_image_url}:${hyperkube_image_tag}
    command:
    - /hyperkube
    - scheduler
    - --config=/etc/kubernetes/configs/kube-scheduler-config.yaml
    - --v=0
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/kubernetes/configs
      name: kubernetes-configurations
      readOnly: true
    - mountPath: /var/lib/kubelet
      name: kubelet-files
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /etc/kubernetes/configs
    name: kubernetes-configurations
  - hostPath:
      path: /var/lib/kubelet
    name: kubelet-files
