kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: true
  webhook:
    enabled: false
  x509:
    clientCAFile: "/etc/kubernetes/ssl/ca.pem"
authorization:
  mode: AlwaysAllow
clusterDNS:
  - "${cluster_dns}"
clusterDomain: "cluster.local"
${feature_gates == "" ? "" : "featureGates:\n  ${feature_gates}"}
readOnlyPort: 10255
serializeImagePulls: false
staticPodPath: "/etc/kubernetes/manifests"
