# https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/ssl/ca.pem"
authorization:
  mode: AlwaysAllow
clusterDNS:${cluster_dns}
clusterDomain: "cluster.local"
${feature_gates == "" ? "" : "featureGates:\n  ${feature_gates}"}
serializeImagePulls: false
staticPodPath: "/etc/kubernetes/manifests"
tlsCertFile: "/etc/kubernetes/ssl/kubelet.pem"
tlsPrivateKeyFile: "/etc/kubernetes/ssl/kubelet-key.pem"

# Resource allocation
cpuManagerPolicy: "static"
systemReserved:
  cpu: "${system_reserved_cpu}"
  memory: "${system_reserved_memory}"
evictionHard:
  memory.available: "1Gi"
  nodefs.available: "2Gi"
evictionSoft:
  memory.available: "2Gi"
  nodefs.available: "4Gi"
evictionSoftGracePeriod:
  memory.available: "1m"
  nodefs.available: "1m"
evictionMaxPodGracePeriod: 30
