#!/bin/sh

textfile_collector_dir=/etc/prom-text-collectors
metric_name=ro_rootfs

ro_rootfs=$(grep " \/ " /proc/mounts | grep "[[:space:]]ro[[:space:],]")
if [ -z "${ro_rootfs}" ]; then
  metric_value=0
else
  metric_value=1
fi

# Write out metrics to a temporary file.
cat << EOF > "${textfile_collector_dir}/${metric_name}.prom.$$"
${metric_name} ${metric_value}
EOF

# Rename the temporary file atomically.
# This avoids the node exporter seeing half a file.
mv "${textfile_collector_dir}/${metric_name}.prom.$$" \
  "${textfile_collector_dir}/${metric_name}.prom"
