kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/ssl/ca.pem"
authorization:
  mode: AlwaysAllow
clusterDNS:
  - "${cluster_dns}"
clusterDomain: "cluster.local"
evictionHard:
  memory.available: "1Gi"
  nodefs.available: "2Gi"
evictionMaxPodGracePeriod: 30
evictionSoft:
  memory.available: "2Gi"
  nodefs.available: "4Gi"
evictionSoftGracePeriod:
  memory.available: "1m"
  nodefs.available: "1m"
${feature_gates == "" ? "" : "featureGates:\n  ${feature_gates}"}
serializeImagePulls: false
staticPodPath: "/etc/kubernetes/manifests"
